# Generated by Django 5.0.7 on 2024-08-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_user_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Mobile', 'Mobile'), ('Stationary', 'Stationary'), ('Animals', 'Animals'), ('Grocery', 'Grocery')], max_length=200, null=True),
        ),
    ]
